version: '3.8'

configs:
  prometheus_config:
    file: ./prometheus.yml

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Anyp4ss!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks: 
      - enpal_net

  # shortner:
  #   container_name: shortner
  #   build:
  #     context: .
  #     dockerfile: src/Api/Dockerfile    
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   ports:
  #     - "5246:80"
  #   networks: 
  #     - enpal_net

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks: 
      - enpal_net
  
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    networks:
      - enpal_net

  grafana:
    image : grafana/grafana
    depends_on: 
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data/:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./config.monitoring
    networks:
      - enpal_net

volumes:
  sqlserver_data:
    driver: local

networks:
  enpal_net:
    driver: bridge

    
